### ISSUE TITLE
Can't resolve 'perf_hooks' in 'lcjs-example-0550-zoombandchart\node_modules\@arction\xydata\dist'

### ISSUE THREAD

**Issue by raygence13** [Arction/lcjs-example-0550-zoombandchart#1]
project serves properly, just receive the following warning

Module not found: Error: Can't resolve 'perf_hooks' in 'E:\projects\lcjs-example-0550-zoombandchart\node_modules\@arction\xydata\dist'
 @ ./src/index.js 19:4-30

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

**Comment by Snekw** [comment]
This warning can be safely ignored. It's caused by xydata library also supporting Node JS with the same files. This results in WebPack finding a Node JS require statement that can't be resolved when bundling for web.

This warning can also be removed by adding additional config to `webpack.config.js`

```js
fallback: {
    'perf_hooks': false
}
```

in `resolve` field of webpack config

```js
resolve: {
    modules: [
        path.resolve('./src'),
        path.resolve('./node_modules')
    ],
    extensions: ['.js'],
    fallback: {
        'perf_hooks': false
    }
},
```
